# docker-compose.yaml

version: '3.8'

services:
  
  telegraf:
    image: telegraf:1.19
    container_name: telegraf
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb
  
  influxdb:
    image: influxdb:2.1.1
    container_name: influxdb
    volumes:
      - influxdb_data:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:${DOCKER_INFLUXDB_INIT_PORT}
  
  grafana:
    image: grafana/grafana
    container_name: grafana-server
    volumes:
     - grafana_data:/var/lib/grafana:rw
    depends_on:
     - influxdb
    ports:
     - ${GRAFANA_PORT}:3000
  
volumes:
  grafana_data:
  influxdb_data:
