name: Execute Performance Test

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#permissions:
#  contents: read

jobs:
  
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Build the stack
#        run: docker-compose up -d

  performance-test:

    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2

#    - name: Run docker-compose
#      run: docker-compose up -d

#    - name: Check running containers before Taurus test execution
#      run: docker ps -a

#    - name: Debug telegraf container
#      run: docker logs telegraf

#    - name: Debug influxdb container
#      run: docker logs influxdb
    
#    - name: Debug grafana-server container
#      run: docker logs grafana-server

#    - name: Get current date
#      id: date
#      run: echo "::set-output name=today::$(date +'%m-%d-%Y')"

    - uses: actions/checkout@v3
    - name: Prepare and execute Taurus test
      uses: Rbillon59/taurus-action@v0.1-beta
      with:
          taurus_project_folder_name: 'taurus/scripts'
          taurus_command_line: execution.yml passfail.yml -report
          blazemeter_api_token: bc42d9e3d91048039e9e9f93:6f477aa6268ed0c8fdcb266945f6804d4d8c7f4b79ac73a3451c97a3267a038ee10e9592
  
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
        channel-id: 'performance-test-as-code'
        # For posting a simple plain text message
        slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

#    - name: Check running containers after Taurus test execution
#      run: docker ps -a